Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2021-08, with the labels that each got.

#67 Fixing broken link
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#70 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/XS, lgtm, approved

#71 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/plugin/manager.go
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#72 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#74 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/S, approved

#78 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#79 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, lgtm, approved

#77 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#73 Updating eventing/serving to v0.25
  pkg/install/install.go
Labels: cla: yes, size/XS, lgtm, approved

#84 Replace manual wait with kind internal wait
  pkg/kind/kind.go
Labels: cla: yes, kind/cleanup, lgtm, size/S, approved

#85 Use multiline string literal for cluster configuration
  pkg/kind/kind.go
Labels: cla: yes, kind/cleanup, lgtm, size/S, approved

#87 Update kourier to v0.25
  pkg/install/install.go
Labels: cla: yes, size/XS, lgtm, approved

#83 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved
