Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2021-06, with the labels that each got.

#1 Add hack scripts, vendor and LICENSE
  LICENSE
  go.mod
  go.sum
  hack/tools.go
  hack/update-deps.sh
  test/presubmit-tests.sh
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/hack/LICENSE
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/hack/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#6 Updating Copyright to 2021
  hack/build-flags.sh
  hack/build.sh
  hack/global_vars.sh
  internal/command/kind.go
  internal/command/version.go
  internal/command/version_test.go
  test/e2e-tests.sh
  test/e2e/basic_flow_test.go
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#11 Install kourier
  pkg/install/install.go
  pkg/kind/kind.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#20 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#22 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/knative.dev/kn-plugin-quickstart/LICENSE
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#15 Install eventing
  pkg/install/install.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#17 Creating kind cluster
  pkg/kind/kind.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#23 Add retries for getting yamls from Github
  pkg/install/install.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#27 print output of kind create commands
  pkg/kind/kind.go
Labels: approved, cla: yes, lgtm, size/S

#24 Cleanup
  go.mod
  pkg/install/install.go
  pkg/kind/kind.go
  third_party/VENDOR-LICENSE/github.com/go-logr/logr/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/apimachinery/pkg/util/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/klog/v2/LICENSE
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/apimachinery/LICENSE
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apimachinery/pkg/util/wait/doc.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#30 Fixing kind create cluster timeout timeout issue
  pkg/install/install.go
  pkg/kind/kind.go
Labels: approved, cla: yes, lgtm, size/M

#26 Kind cluster install options
  pkg/install/install.go
  pkg/kind/kind.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#29 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#25 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#32 Localize kourier-ingress service
  pkg/install/install.go
  pkg/kind/kind.go
Labels: approved, cla: yes, lgtm, size/M

#34 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS
