Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2021-07, with the labels that each got.

#35 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/S

#36 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#40 Adding instructions to README
  README.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/M

#41 drop releasibility action
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/L

#46 fix for failing prow auto-release job
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#45 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#42 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#43 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/L

#56 Create example broker
  pkg/install/install.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#59 adding retry for kourier install
  pkg/install/install.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#58 update to latest knative 0.24
  pkg/install/install.go
Labels: approved, cla: yes, lgtm, size/S

#49 updating readme to include release page, better instructions
  README.md
Labels: approved, cla: yes, lgtm, size/M

#52 Fix plugin version info
  hack/build-flags.sh
  hack/release.sh
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#48 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#47 update owners to include kn plugin approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#63 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/kn/plugin/manager.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#64 adding success message when job finishes successfully
  pkg/kind/kind.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#65 Adding back original installation text
  pkg/install/install.go
  pkg/kind/kind.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/S
