Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2021-11, with the labels that each got.

#150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S, approved

#152 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, size/L, approved

#154 Document maturity levels in sandbox
  README.md
Labels: cla: yes, size/XS, lgtm, approved

#153 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#155 Update knative components to 1.0
  pkg/install/install.go
Labels: cla: yes, kind/enhancement, lgtm, size/S, approved

#156 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S, approved

#158 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, size/L, approved

#159 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#160 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/S, approved

#161 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, lgtm, approved

#164 Use sslip.io for domain
  pkg/install/install.go
Labels: cla: yes, kind/cleanup, size/XS, lgtm, approved

#165 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#169 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#171 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/M, lgtm, approved

#172 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#170 Adds macOS (arm64) plugin build
  hack/release.sh
Labels: cla: yes, kind/enhancement, size/XS, lgtm, approved

#173 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#174 Publish kn-quickstart-darwin-arm64 artifact
  hack/release.sh
Labels: cla: yes, size/XS, lgtm, approved

#175 Pause for minikube tunnel setup on mac/windows
  pkg/minikube/minikube.go
Labels: cla: yes, lgtm, size/S, approved

#179 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#180 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/XS, lgtm, approved
