Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2021-10, with the labels that each got.

#116 Fixing release script
  hack/release.sh
Labels: cla: yes, size/XS, lgtm, approved

#117 More fixing of release script
  hack/release.sh
Labels: cla: yes, size/XS, lgtm, approved

#121 Ignore releasabilty job until on release train
  .gitignore
Labels: cla: yes, size/XS, lgtm, approved

#134 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#132 Remove duplicate minikube tunnel
  pkg/minikube/minikube.go
Labels: cla: yes, kind/bug, size/XS, lgtm, approved

#139 Manual minikube tunnel command for windows/mac
  README.md
  pkg/install/install.go
  pkg/minikube/minikube.go
Labels: cla: yes, kind/cleanup, size/M, lgtm, approved
