Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2021-09, with the labels that each got.

#86 Deduplicate kubectl functions and simplify retrying applies
  go.mod
  pkg/install/install.go
  third_party/VENDOR-LICENSE/github.com/go-logr/logr/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/apimachinery/pkg/util/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/klog/v2/LICENSE
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/apimachinery/LICENSE
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apimachinery/pkg/util/wait/doc.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: cla: yes, kind/cleanup, lgtm, size/XXL, approved

#90 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#94 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/S, approved

#95 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, size/S, approved

#96 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/XS, lgtm, approved

#98 Updating install location to PATH instead of plugin directory
  README.md
Labels: cla: yes, size/XS, lgtm, approved

#99 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, size/S, approved

#89 Adding version info to plugin
  hack/README.md
  hack/build.sh
  hack/global_vars.sh
  hack/release.sh
  hack/tools.go
Labels: cla: yes, kind/bug, lgtm, size/L, approved

#100 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#101 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/S, approved

#102 remove releasability
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, size/L, approved

#93 Setting timeout for waitForPodsReady to 5min
  pkg/install/install.go
Labels: cla: yes, kind/enhancement, size/XS, lgtm, approved

#105 Fixing bug where cluster created twice
  pkg/minikube/minikube.go
Labels: cla: yes, kind/bug, size/XS, lgtm, approved

#107 Update to knative 0.26
  pkg/install/install.go
Labels: cla: yes, size/XS, lgtm, approved

#110 Fixing minikube driver config screen text
  pkg/minikube/minikube.go
Labels: cla: yes, size/XS, lgtm, approved

#115 Fixing version info & adding support for Apple silicon
  hack/build-flags.sh
  hack/release.sh
Labels: cla: yes, kind/bug, lgtm, size/S, approved
