Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2021-12, with the labels that each got.

#183 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#184 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#182 Update K8s version, provide multi-arch support for kind
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: cla: yes, size/XS, lgtm, approved

#185 Fix some stray references to minikube-knative profile
  pkg/install/install.go
  pkg/minikube/minikube.go
Labels: size/XS, lgtm, approved

#187 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/L, approved

#186 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#188 Add instruction to keep minikube tunnel terminal open
  pkg/minikube/minikube.go
Labels: size/XS, lgtm, approved

#191 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#192 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#193 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#195 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#194 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved
