Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-03, with the labels that each got.

#236 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#226 Use minikube config value for k8s version if present
  pkg/minikube/minikube.go
Labels: lgtm, size/S, approved

#237 Updates to kubernetes v1.23 and minikube to v1.25
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: size/XS, lgtm, approved

#238 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#239 Adds a command line flag to set k8s version
  internal/command/flags.go
  internal/command/kind.go
  internal/command/minikube.go
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: kind/enhancement, size/M, lgtm, approved

#241 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#242 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#244 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#245 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#247 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#250 adds check for kubectl
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: lgtm, size/S, approved

#249 allows use of minikube config for cpus/memory
  pkg/minikube/minikube.go
Labels: size/M, lgtm, approved

#251 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#253 [release-1.3] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#254 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#255 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: size/XS, lgtm, approved

#256 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#257 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, size/XL, approved

#258 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/modules.txt
Labels: size/M, lgtm, approved
