Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-06, with the labels that each got.

#295 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#296 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#278 Add serving e2e test
  .github/workflows/kind-e2e.yaml
  test/eventing-e2e-test.sh
  test/serving-e2e-test.sh
Labels: lgtm, size/L, approved

#297 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#298 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#301 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#300 Require manual minikube tunnel on linux too
  pkg/install/install.go
  pkg/minikube/minikube.go
Labels: lgtm, size/S, approved

#303 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#304 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved
