Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-10, with the labels that each got.

#345 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#346 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#347 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#348 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#349 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#351 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#352 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#353 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#356 Fixes build flags in release script
  hack/release.sh
Labels: kind/cleanup, size/XS, lgtm, approved

#360 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved
