Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-07, with the labels that each got.

#305 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#306 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#307 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#310 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: size/M, lgtm, approved

#311 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/L, approved

#312 update knative.dev/hack
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#313 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
