Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-01, with the labels that each got.

#198 Update components to v1.1
  pkg/install/install.go
Labels: size/XS, lgtm, approved

#200 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#201 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, size/L, approved

#202 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#203 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#204 Use shared hack functions in build
  hack/build.sh
Labels: size/XS, lgtm, approved

#205 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, lgtm, approved

#207 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#208 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#189 Updates minikube tunnel display prompt
  pkg/minikube/minikube.go
Labels: size/XS, lgtm, approved

#209 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#210 Updates knative components to v1.2
  pkg/install/install.go
Labels: size/XS, lgtm, approved

#212 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#211 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/L, approved

#214 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, lgtm, approved

#213 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#215 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#216 hack/build.sh: improve portability
  hack/build.sh
Labels: kind/cleanup, size/XS, ok-to-test, lgtm, approved

#217 clusterNameOption(): simplify interface
  internal/command/flags.go
  internal/command/kind.go
  internal/command/minikube.go
Labels: kind/cleanup, size/XS, ok-to-test, lgtm, approved
