Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-09, with the labels that each got.

#328 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#330 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#333 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#334 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#335 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#336 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#339 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/MAINTAINERS
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/knative.dev/client/pkg/kn/plugin/manager.go
  vendor/knative.dev/client/pkg/kn/plugin/verify.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#340 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/active_help.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/assert_go113.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/compare_go113.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/internal/assert/assert.go
  vendor/gotest.tools/v3/internal/assert/result.go
  vendor/gotest.tools/v3/internal/source/defers.go
  vendor/gotest.tools/v3/internal/source/source.go
  vendor/gotest.tools/v3/internal/source/update.go
  vendor/gotest.tools/v3/internal/source/version.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#341 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#342 Fix cut command in build-flags script
  hack/build-flags.sh
Labels: kind/enhancement, size/XS, lgtm, approved

#343 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#344 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
