Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-08, with the labels that each got.

#314 Add links to nightlies
  README.md
Labels: lgtm, size/S, approved

#315 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#316 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#317 Updates kubernetes version to v1.24.3
  .github/workflows/kind-e2e.yaml
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: lgtm, size/S, approved

#318 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#319 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#320 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#321 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#323 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#324 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#325 Update knative versions to v1.7
  pkg/install/install.go
Labels: size/XS, lgtm, approved

#327 Determine latest component versions automatically
  hack/build-flags.sh
  hack/build.sh
  pkg/install/install.go
Labels: size/M, lgtm, approved
