Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-02, with the labels that each got.

#218 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#219 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/M, lgtm, approved

#220 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#221 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#225 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#228 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#232 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#231 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#234 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/value/name.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#233 remove default duplicated in clusterNameOption flag
  internal/command/flags.go
Labels: size/XS, lgtm, approved

#235 Updates go to v1.16
  go.mod
  go.sum
  hack/build.sh
Labels: lgtm, size/L, approved
