Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-05, with the labels that each got.

#279 Adds flags for installing knative a la carte
  internal/command/flags.go
  internal/command/kind.go
  internal/command/minikube.go
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: size/M, lgtm, approved

#283 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#284 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#285 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#287 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#288 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#289 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#290 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#293 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#294 update knative to 1.5
  pkg/install/install.go
Labels: size/XS, lgtm, approved
