Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2022-04, with the labels that each got.

#259 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, size/S, approved

#261 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, size/L, approved

#262 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#263 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#264 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#266 Adds kubectl and kind/minikube requirement to README
  README.md
Labels: size/XS, lgtm, approved

#268 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#270 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#271 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/gotest.tools/v3/assert/assert_go113.go
  vendor/gotest.tools/v3/assert/cmp/compare_go113.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#272 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, lgtm, approved

#273 Upgrade Go to 1.17
  go.mod
  vendor/github.com/mitchellh/go-homedir/go.mod
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/go.sum
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#275 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/L, approved

#274 Update knative components to v1.4
  pkg/install/install.go
Labels: size/XS, lgtm, approved

#277 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#280 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#281 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved
