Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2023-01, with the labels that each got.

#376 #374: Add local registry support
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: size/M, ok-to-test, lgtm, approved

#380 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#381 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#383 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#379 #97: Added soft abort to installation if knative exists
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: ok-to-test, lgtm, size/L, approved

#384 Replace references to knative.dev/client to knative.dev/client-pkg
  .gitignore
  go.mod
  go.sum
  pkg/plugin/plugin.go
  third_party/VENDOR-LICENSE/github.com/mitchellh/go-homedir/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/client-pkg/pkg/kn/plugin/LICENSE
  vendor/github.com/mitchellh/go-homedir/LICENSE
  vendor/github.com/mitchellh/go-homedir/README.md
  vendor/github.com/mitchellh/go-homedir/homedir.go
  vendor/knative.dev/client-pkg/LICENSE
  vendor/knative.dev/client-pkg/pkg/kn/plugin/types.go
  vendor/knative.dev/client/pkg/kn/plugin/manager.go
  vendor/knative.dev/client/pkg/kn/plugin/stat.go
  vendor/knative.dev/client/pkg/kn/plugin/stat_windows.go
  vendor/knative.dev/client/pkg/kn/plugin/verify.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, size/XXL, approved
