Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2023-03, with the labels that each got.

#398 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#394 [release-1.9] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/L, approved

#390 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, skip-review

#399 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#395 [release-1.8] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#396 Disable e2e test due to issue with action runner
  .github/workflows/kind-e2e.yaml
Labels: size/M, lgtm, approved

#400 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#401 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/XL, approved
