Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2023-07, with the labels that each got.

#426 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#427 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#428 Make kind local registry optional
  internal/command/flags.go
  internal/command/kind.go
  pkg/kind/kind.go
Labels: size/M, lgtm, approved

#432 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#433 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/XL, approved
