Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2023-11, with the labels that each got.

#465 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#466 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#468 Add localhost registry to the set avoiding tag resolution as a workaround for #467
  pkg/install/install.go
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: kind/bug, lgtm, size/S, approved

#472 kind local registry setup update on Readme.md #453
  README.md
Labels: size/XS, ok-to-test, lgtm, approved

#473 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, lgtm, approved

#475 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#474 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#476 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
