Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2024-01, with the labels that each got.

#478 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#481 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#482 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#479 Update kind/minikube/k8s versions
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: size/XS, lgtm, approved

#486 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#483 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#487 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#488 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#489 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved
