Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2024-06, with the labels that each got.

#520 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#522 Kind Quickstart: Add `extraMount` Option
  README.md
  internal/command/flags.go
  internal/command/kind.go
  pkg/kind/kind.go
Labels: kind/enhancement, size/M, ok-to-test, lgtm, approved

#523 bump minikube/kind kubernetes to v1.30
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: size/XS, lgtm, approved

#525 Run registry as bridge network
  pkg/kind/kind.go
Labels: size/XS, lgtm, approved

#521 Adding a new Minikube flag for helm chart install of Apache Camel K
  README.md
  internal/command/flags.go
  internal/command/minikube.go
  pkg/install/install.go
  pkg/minikube/minikube.go
Labels: size/M, lgtm, approved
