Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2024-11, with the labels that each got.

#552 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#553 Revert Camel K flag
  README.md
  internal/command/flags.go
  internal/command/minikube.go
  pkg/install/install.go
  pkg/minikube/minikube.go
Labels: size/M, lgtm, approved

#554 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
