Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2024-04, with the labels that each got.

#506 Update to latest dependecies
  go.mod
  go.sum
  pkg/plugin/plugin.go
  third_party/VENDOR-LICENSE/github.com/mitchellh/go-homedir/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/client-pkg/pkg/plugin/LICENSE
  vendor/github.com/mitchellh/go-homedir/LICENSE
  vendor/github.com/mitchellh/go-homedir/README.md
  vendor/github.com/mitchellh/go-homedir/homedir.go
  vendor/knative.dev/client-pkg/pkg/kn/plugin/types.go
  vendor/knative.dev/client-pkg/pkg/plugin/context_sharing_types.go
  vendor/knative.dev/client-pkg/pkg/plugin/manager.go
  vendor/knative.dev/client-pkg/pkg/plugin/stat.go
  vendor/knative.dev/client-pkg/pkg/plugin/stat_windows.go
  vendor/knative.dev/client-pkg/pkg/plugin/verify.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#507 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#510 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#509 Bump minikube/kind kubernetes to v1.28
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: kind/cleanup, size/XS, lgtm, approved

#511 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#512 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#513 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
