Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2025-09, with the labels that each got.

#597 [release-1.19] Upgrade to latest dependencies [skip-dot-release]
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, skip-review

#599 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#602 Fix: update minimum k8 version to fix timeouts, add versions to documentation and fix broken link.
  README.md
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: kind/bug, size/M, ok-to-test, lgtm, kind/documentation, approved

#605 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/time.go
  vendor/golang.org/x/sys/unix/affinity_linux.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/XXL, skip-review
