Repository knative-extensions/kn-plugin-quickstart, pull requests merged in 2025-04, with the labels that each got.

#575 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#573 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/boilerplate.go.txt
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#579 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#580 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#576 bump kubernetes to v1.31
  pkg/kind/kind.go
  pkg/minikube/minikube.go
Labels: size/XS, lgtm, approved

#577 bump to golangci yaml v2
  .golangci.yaml
Labels: size/M, lgtm, approved

#581 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved
